# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
      - cron: "0 0 */1 * *"


jobs:
  update-blog-posts:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Git pull to fetch the latest changes
        run: git pull

      - name: Run Update Python Script
        run: python main.py

      - name: Debug - Display README.md content
        run: cat README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "ehgur062300@gmail.com"
          git config --local user.name "ehgur062300"
          git add README.md
          git diff
          git commit -m "Update Blog Posts" -a
          git push
